### PR TITLE
Fix indexing with Slice

### LINKED ISSUE #209: Latest release causes StackOverflowError
The CI tests of MCMCChains reveal a StackOverflowError on Julia 1.0 that was introduced in the latest release (1.6.0) of OffsetArrays and was not present in version 1.5.3. E.g., the following test with OffsetArrays 1.6.0 fails (https://github.com/TuringLang/MCMCChains.jl/pull/265/checks?check_run_id=1972763807) whereas this test (https://github.com/TuringLang/MCMCChains.jl/runs/1890809139) with OffsetArrays 1.5.3 was successful.

According to the logs, https://github.com/JuliaArrays/OffsetArrays.jl/blob/c805039afba6b1b02aa9ad4e931820a4d1e0fa28/src/OffsetArrays.jl#L356 causes the stackoverflow error (corresponds to https://github.com/JuliaArrays/OffsetArrays.jl/blob/ee0dced602cc666b72cf56e86e270ead3e82d741/src/OffsetArrays.jl#L352 on master).

### PR DESCRIPTION
**Pull request by jishnub**
Fixes #209 

On master and Julia 1.0

```julia
julia> using OffsetArrays

julia> r = 1:2:10
1:2:9

julia> r[Base.Slice(Base.OneTo(3))]
ERROR: StackOverflowError:
Stacktrace:
 [1] getindex(::StepRange{Int64,Int64}, ::Base.Slice{Base.OneTo{Int64}}) at /home/jishnu/Dropbox/JuliaPackages/OffsetArrays.jl/src/OffsetArrays.jl:352 (repeats 80000 times)
```

After this PR:

```julia
julia> using OffsetArrays

julia> r = 1:2:10
1:2:9

julia> r[Base.Slice(Base.OneTo(3))]
1:2:5 with indices 1:3
```

### CODE REVIEW

**Review by timholy — COMMENTED** [review]
I ended up having to try the tests to understand this, but now that I do the one thing I'd request is adding
```julia
r2 = IdentityUnitRange(2:10)
```
and
```julia
r2 = IdOffsetRange(Base.OneTo(9), 1)
```
to the tests. My reading is that it should still work, but given that `no_offset_view` performs "real work" in these cases that's a bit different from what's in the test coverage, I think we should check.

**Comment by jishnub** [comment]
I've added tests for `IdOffsetRange(::Base.OneTo(9), offset)`. Some tests for `r2 = IdentityUnitRange(2:10)` were already there, but now I've added some other `r1` types to make the tests for `r1[r2]` more robust.

**Review by timholy — APPROVED** [review]

**Comment by rikhuijzer** [comment]
Thanks a lot for fixing this so quickly :smile: Could you also tag the patch? CI is still failing at https://github.com/TuringLang/MCMCChains.jl.

**Comment by rikhuijzer** [comment]
@jishnub

**Comment by timholy** [comment]
https://github.com/JuliaRegistries/General/pull/30890

**Pull request merged**
