### PR TITLE
add Origin to specify the origin of output OffsetArray

### LINKED ISSUE #132: support CartesianIndex offset
The following usage could be helpful to deal with multi-dimensional arrays

`OffsetArray(rand(4, 4), CartesianIndex(-1, -1))`

I could do it later if you think this is a good idea.

### PR DESCRIPTION
**Pull request by johnnychen94**
closes #132

### CODE REVIEW

**Comment by jishnub** [comment]
This looks great! I'm just wondering if the name `OffsetOrigin` is a bit confusing, as it seems to indicate that the origin of the array is being offset by a certain amount, however what it really does is to relocate the origin to the specified `CartesianIndex`.

**Comment by johnnychen94** [comment]
The ambiguity might come from the fact that "offset" can also be a verb. I originally thought it was okay because `OffsetOrigin` is a type and not a function.

I mean, `OffsetOrigin(a, (0, 0))` can be confusing. But `OffsetArray(a, OffsetOrigin(0, 0))` looks fine to me.

I'm not a native speaker 😂 I'm really bad at naming. Do you have any suggestions?

**Comment by jishnub** [comment]
I'm not a native speaker either :laughing: perhaps use just `Origin` that is unambiguously a noun? Is this clashing with any other package?

**Comment by johnnychen94** [comment]
> Is this clashing with any other package?

That's my main consideration for the `Offset` prefix... To clearly mark it as a name related to`OffsetArrays`.

**Comment by jishnub** [comment]
I guess this is fine. We may add some keyword-based constructors to simplify the process. Eg.

```julia
julia> OffsetArray(zeros(2,2), offsets = (2,2))
2×2 OffsetArray(::Array{Float64,2}, 3:4, 3:4) with eltype Float64 with indices 3:4×3:4:
 0.0  0.0
 0.0  0.0

julia> OffsetArray(zeros(2,2), origin = (2,2))
2×2 OffsetArray(::Array{Float64,2}, 2:3, 2:3) with eltype Float64 with indices 2:3×2:3:
 0.0  0.0
 0.0  0.0
```

In this case we don't even need to export the types.

**Comment by johnnychen94** [comment]
> We may add some keyword-based constructors to simplify the process

Remove the `OffsetArray(A, ZeroBasedIndex)`  usage or still keep it? I think we should only keep one of it.

**Comment by jishnub** [comment]
I would say keep `ZeroBasedIndex`, but as an unexported constant. The form is certainly convenient for someone starting off from python etc. We perhaps don't need `OneBasedIndex`.

**Comment by johnnychen94** [comment]
Sorry for the inaccurate question. Let me ask again about the API we're going to take.

I've added both APIs in 67c13a2 but I'm not very satisfied with it. Here are the questions:

* do we need to keep both APIs? `OffsetArray(a, OffsetOrigin(-1, 2))` and `OffsetArray(a; origin=(-1, 2))`
  * if so, do we need to export `OffsetOrigin`, `ZeroBasedIndexing`? If not, then it would be likely that nobody will try to use this API.
* does `OffsetArray(a, origin=0)` look strange to you for high dimensional `a`?

I feel we should only keep one of `OffsetArray(a, origin=index)` and `OffsetArray(a, OffsetOrigin(index))`. I'm now a little bit don't like the keyword version because it provides two equivalent ways to pass offsets: `OffsetArray(a, indices...)` and `OffsetArray(a, offsets=indices)`.

ping @timholy for a final review as this PR adds new exports.

**Comment by jishnub** [comment]
Regarding the second point, I'll say that `OffsetArray(a, origin=0)` does look strange. It should be possible to use something like `OffsetArray(a, origin = ntuple(x->0, ndims(a)))`. I'd say that it's reasonable to expect the value passed to origin to be a `NTuple{ndims(a),Int}`.

Regarding whether to add the keyword-based constructor at all, this is something that I don't have a strong opinion about, but I feel that the keyword-based versions does make it easier to understand what's going on without necessarily being familiar with the package. However this is a matter of taste, and given that the positional-argument version has been standardized maybe we can stick to that. In this case we'll perhaps have to export the types.

On that note, I actually don't mind these not being exported. Something like this seems pretty clear to me:

```julia
julia> OffsetArray(a, OffsetArrays.Origin(0,0))
```

This also sidesteps the issue of having to prepend `Offset` to the name of the type to denote the association.

I'm not sure what constitutes the API: exported types or documented types? If this usage is documented, would it still not be used if the type is not exported?

Regarding `OneBasedIndexing` -- do we need this at all?

**Comment by johnnychen94** [comment]
`OffsetArrays.Origin(0,0)` looks good to me. I'll revert `67c13a2` and stick to the positional version.

> Regarding OneBasedIndexing -- do we need this at all?

I feel it awkward to only define `ZeroBasedIndexing` given that the major part of Julia lives in the `OneBasedIndexing` world :joy:

Perhaps not define both of them in this PR, and try `OffsetArrays.Origin` for a while and see if we really want that.

> I'm not sure what constitutes the API: exported types or documented types? If this usage is documented, would it still not be used if the type is not exported?

* Exported names are definitely belong to the APIs. It is very hard to deprecate/remove exported names, so it should be considered the stablest one.
* undocumented internal names should not be considered stable. More often, we would explicitly tag internal-only functions with leading `_`(s) on its name. Speaking of this, it is more clear that `splitCartesianIndices` is an internal helper function if we rename it to `_splitCartesianIndices`.
* Whether documented non-export names are part of the API specifications is more often a personal taste. There are cases that we have good reason to not export them, for example, `ImageFiltering.Kernel.*` is not exported, but that's a part of the API.

`OffsetArrays.Origin` should not be exported because it is less clear what it means without the module namespace. But it should be a part of the API, just like `ImageFiltering.Kernel`.

**Comment by johnnychen94** [comment]
The nightly test failure on macOS is not related; I've verified it locally.

**Pull request merged**
