### PR TITLE
Idempotent indexing in range[IdOffsetRange]

### PR DESCRIPTION
**Pull request by jishnub**
After this PR:

```julia
julia> r = OffsetArrays.IdOffsetRange(3:5, -1)
OffsetArrays.IdOffsetRange(2:4)

julia> (1:4)[r]
2:4 with indices 0:2

julia> axes((1:4)[r]) == axes(r)
true
```

On master:

```julia
julia> (1:4)[r]
2:4
```

As a consequence, 

on master:

```julia
julia> a = zeros(2:4);

julia> r = 1:4;

julia> a[axes(a,1)] .= r[axes(a,1)]
ERROR: DimensionMismatch("array could not be broadcast to match destination")
```

after this PR:

```julia
julia> a = zeros(2:4);

julia> r = 1:4;

julia> a[axes(a,1)] .= r[axes(a,1)]
3-element view(OffsetArray(::Array{Float64,1}, 2:4), 2:4) with eltype Float64 with indices 2:4:
 2.0
 3.0
 4.0
```

### CODE REVIEW

**Comment by jishnub** [comment]
bump

**Review by johnnychen94 — APPROVED** [review]
This looks really nice a fix to me but I'd still want to invite @timholy to double-check it.

**Comment by timholy** [comment]
It's a bit suspicious that the bodies of all the new methods are identical. Can you instead modify the generic `AbstractRange` methods above to achieve the same thing?

**Comment by jishnub** [comment]
It appears to be a bit difficult to achieve this in general without introducing ambiguities, as some of the range types have specific indexing behaviors defined in `Base`. Eg: 

```julia
function getindex(r::StepRange, s::AbstractRange{<:Integer})
```

and 

```julia
function getindex(r::StepRangeLen{T,<:TwicePrecision,<:TwicePrecision}, s::OrdinalRange{<:Integer}) where T
```

presumably indicate that we should specialize on the second argument?

**Comment by timholy** [comment]
Ah, yeah, good point. At some point we probably want to have some tests for this kind of thing that introduce a novel range object (could use https://github.com/JuliaArrays/CustomUnitRanges.jl to make that easy), just to make sure we go as far as we can with generic operations.

**Comment by timholy** [comment]
I have no other objections, though. This clearly improves the handling of range values and range indices :+1:. So merge at will.

**Comment by jishnub** [comment]
Yes indeed. The present approach is patchwork at best, and a new range type introduced will not support idempotent indexing with an `IdOffsetRange`. I wonder what's the best approach to address this?

For example:

```julia
julia> struct MyUnitRange <: AbstractUnitRange{Int}
       start :: Int
       stop :: Int
       end

julia> Base.first(r::MyUnitRange) = r.start

julia> Base.last(r::MyUnitRange) = r.stop

julia> s = MyUnitRange(2,3);

julia> r = OffsetArrays.IdOffsetRange(4:5, -3)
OffsetArrays.IdOffsetRange(1:2)

julia> axes(r)
(OffsetArrays.IdOffsetRange(-2:-1),)

julia> s[r]
2:3

julia> axes(s[r])
(Base.OneTo(2),)
```

Ideally we should be able to define 

```julia
getindex(r::AbstractRange, inds::IdOffsetRange)
```
however the problem with this is that a type that defines 

```julia
getindex(r::CustomRange, inds::AbstractUnitRange{<:Integer})
```
will run into ambiguities.

**Comment by johnnychen94** [comment]
I'm still a little confused about how things are working under the hood, but tests look good. Very concise a patch, I agree that we need tests to make sure things don't get break unexpectedly.

**Comment by timholy** [comment]
I suspect it's a sign we may need better "inner methods" and implement the core range algorithms with them...although ranges are already pretty close to the metal. I suspect this is a multistage process, where we get this working and then rethink range implementation in Base.

**Comment by jishnub** [comment]
I've added methods that return an `AbstractUnitRange` instead of an `OffsetArray` when a `UnitRange{<:Integer}` is indexed with an `IdOffstRange` or an `IdentityUnitRange`. This is because the result may be further used in indexing, and indexing with ranges is faster than that with vectors.

before
```julia
julia> a = collect(1:10);

julia> ur = 3:6;

julia> idr = Base.IdentityUnitRange(2:4);

julia> @btime $a[$ur[$idr]];
  98.796 ns (1 allocation: 112 bytes)

julia> idor = OffsetArrays.IdOffsetRange(1:3, 1);

julia> @btime $a[$ur[$idor]];
  102.616 ns (1 allocation: 112 bytes)
```

after
```julia
julia> @btime $a[$ur[$idr]];
  76.405 ns (1 allocation: 112 bytes)

julia> @btime $a[$ur[$idor]];
  84.349 ns (1 allocation: 112 bytes)
```

**Comment by timholy** [comment]
This is great work, thanks @jishnub!

**Comment by johnnychen94** [comment]
A new patch release, maybe?

**Pull request merged**
