### PR TITLE
show type for IdOffsetRange

### LINKED ISSUE #121: `show(::OffsetArrays.IdOffsetRange` should show its type
```julia
import OffsetArrays

julia> Base.OneTo(3)
Base.OneTo(3)

julia> Base.IdentityUnitRange(1:3)
Base.IdentityUnitRange(1:3)

julia> OffsetArrays.IdOffsetRange(1:3)
1:3
```

I think this might be misleading, as I mentioned in https://github.com/JuliaArrays/OffsetArrays.jl/issues/120#issuecomment-643510513

### PR DESCRIPTION
**Pull request by jishnub**
This PR attempts to fix #121 . Now we have 

```julia
julia> a = OffsetArray([1 2; 3 4], -1:0, 5:6)
2×2 OffsetArray(::Array{Int64,2}, -1:0, 5:6) with eltype Int64 with indices -1:0×5:6:
 1  2
 3  4

julia> axes(a)
(OffsetArrays.IdOffsetRange(-1:0), OffsetArrays.IdOffsetRange(5:6))
```

### CODE REVIEW

**Comment by jishnub** [comment]
This PR alleviates [this issue in #120 ](https://github.com/JuliaArrays/OffsetArrays.jl/issues/120#issuecomment-643510513) :

Previously

```julia
julia> @test 1:3 === OffsetArrays.IdOffsetRange(1:3)
Test Failed at none:1
  Expression: 1:3 === OffsetArrays.IdOffsetRange(1:3)
   Evaluated: 1:3 === 1:3
ERROR: There was an error during testing
```

Now 

```julia
julia> @test 1:3 === OffsetArrays.IdOffsetRange(1:3)
Test Failed at REPL[12]:1
  Expression: 1:3 === OffsetArrays.IdOffsetRange(1:3)
   Evaluated: 1:3 === OffsetArrays.IdOffsetRange(1:3)
ERROR: There was an error during testing
```

**Review by johnnychen94 — APPROVED** [review]
Thanks for doing this! I was planning to fix these after finishing my little DemoCards project but you certainly did a great job here!

Could possibly add some show tests to capture the patterns as a regression test. The tools I'd personally use is`Suppressor.@capture`, or `ReferenceTests`'s `@io2str`/`@test_reference`.

You're doing great here, feel free to merge at will.

**Comment by johnnychen94** [comment]
FYI you could use `git rebase master` in `showIdOffsetRange` branch to keep a clean commit history.

**Comment by jishnub** [comment]
I think we need to update the docs to reflect this change

**Pull request merged**
