### PR TITLE
eltype and ndims of an OffsetArray matches that of the parent

### LINKED ISSUE #162: Element type of an OffsetArray must match that of the parent array
`OffsetArray` merely provides a map between indices, so it should always have the same element type as the parent array. Currently something like this is possible:

```julia
julia> b = OffsetArray{Float64,2,Matrix{ComplexF64}}(zeros(ComplexF64,2,2), (1,1))
2×2 OffsetArray(::Array{Complex{Float64},2}, 2:3, 2:3) with eltype Float64 with indices 2:3×2:3:
 0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im

julia> b[1]
0.0 + 0.0im

julia> eltype(b)
Float64
```

This should be a bug. Would disallowing this be construed as a breaking change?

### PR DESCRIPTION
**Pull request by jishnub**
Fixes #162 

Now 

```julia
julia> OffsetMatrix{Float64, Matrix{ComplexF64}}
ERROR: TypeError: in Type, in AA, expected AA<:AbstractArray{Float64,2}, got Type{Array{Complex{Float64},2}}
```

also,

```julia
julia> OffsetMatrix{Float64, Vector{Float64}}
ERROR: TypeError: in Type, in AA, expected AA<:AbstractArray{Float64,2}, got Type{Array{Float64,1}}
```

### CODE REVIEW

**Comment by jishnub** [comment]
Leaving open as I'm not entirely sure if there are cases where the `ndims` might not be identical

**Review by johnnychen94 — APPROVED** [review]
I don't think we need that much flexibility here.

There are many ways to insert the missing dimension without memory allocation, e.g.,

```julia
Base.ReshapedArray(A, (1, 4, 4), ())
```

**Comment by timholy** [comment]
Better to call `reshape`, though, rather than the constructor itself. Normal users don't want to have to deal with `Base.MultiplicativeInverses`.

**Review by timholy — APPROVED** [review]

**Comment by timholy** [comment]
Hmm, this turned out to be pretty breaking for a patch release (at least for ImageCore). In retrospect we should have bumped to 1.4.

**Comment by jishnub** [comment]
I'm not familiar with ImageCore, could you point me towards an example that breaks as a consequence of this change?

**Comment by johnnychen94** [comment]
https://github.com/JuliaImages/ImageCore.jl/pull/149, no worries, that breakage is expected and is fixable. Just that this patch release breaks something...

**Comment by timholy** [comment]
Yep, @johnnychen94 is right. Really, it was misguided of OffsetArrays to implement those methods in the first place.

I've released my share of patch releases that broke something. Just thought I'd mention it since these questions of what to call releases come up all the time (typically, without a crystal-clear answer).

**Pull request merged**
